import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/Components/header/Header";
import Footer from "@/Components/Footer";
import Layout from "@/Components/Layout";
import { Toaster } from "react-hot-toast";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "ShopCart - eCommerce website",
  description: "Generated by CodeCommandBD",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Layout>
          <Header></Header>
          {children}
          <Footer></Footer>
          <Toaster position="bottom-right" toastOptions={{
            duration:3000,
            style:{background:'#8e00ee',color:'#FFF'}
          }} />
        </Layout>
      </body>
    </html>
  );
}
